# Generated by Django 4.2.17 on 2024-12-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=36)),
                ('username', models.CharField(max_length=50)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('input_link', models.URLField()),
            ],
        ),
    ]
