# Generated by Django 4.2.17 on 2024-12-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visualize_link',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
