# Generated by Django 4.2.17 on 2024-12-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_job_visualize_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='visualize_link',
        ),
        migrations.AddField(
            model_name='job',
            name='output_link',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='input_link',
            field=models.CharField(max_length=250),
        ),
    ]
