# Generated by Django 4.2.17 on 2024-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_alter_job_out_time_alter_job_output_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input_link',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_link',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
